[project]
name = "tms_app"
authors = [
    { name = "Muhammad Faizan" }
    ]
    description = "Transport Management System for bus ticketing, cargo booking and live tracking, built on Frappe/ERPNext"
    requires-python = ">=3.10"
    readme = "README.md"
    dynamic = ["version"]
    dependencies = [
        "frappe",
        ]

        [build-system]
        requires = ["flit_core>=3.4,<4"]
        build-backend = "flit_core.buildapi"

        [tool.bench.dev-dependencies]
        
