[project]
name = "tms_app"
authors = [
    { name = "Muhammad Faizan" }
    ]
    description = "Transport Management System for bus ticketing, cargo booking and live tracking, built on Frappe/ERPNext"
    requires-python = ">=3.10"
    readme = "README.md"
    dynamic = ["version"]
    dependencies = [
        "frappe",
        ]

        [build-system]
        requires = ["setuptools>=61.0.0"]
        build-backend = "setuptools.build_meta"

        [tool.setuptools]
        packages = ["tms_app"]
        include-package-data = true

        [tool.setuptools.dynamic]
        version = {attr = "tms_app.__version__"}
        
